pipeline{
    agent any

    tools{
        maven "mvn"
    }
    environment{
        jarloacation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Maven in Jenkins\\target"
    }
    stages{
        stage('Build'){
            steps{
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'

                bat 'mvn clean test package'
            }
        }
    }
    post{
        success{
            bat 'java -jar %jarlocation%'
        }
    }
}
