pipeline{
    agent any
    
    tools{
        maven "Maven"
    }
    environment{
        jarloacation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\sample-maven-job\\target\\my-app-1.0-SNAPSHOT.jar"
    }
    
    stages{
        stage('Build'){
            steps{
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'

                bat 'mvn clean test package'
            }
        }
    }
    post{
        success{
            bat 'java -jar %jarloacation%'
        }
    }
}
