pipeline{
    agent any
    
    jarloacation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Maven in Jenkins\\target\\my-app-1.0-SNAPSHOT.jar"

    tools{
        maven "Maven"
    }
    environment{
        def jarloacation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Maven in Jenkins\\target\\my-app-1.0-SNAPSHOT.jar"
    }
    
    stages{
        stage('Build'){
            steps{
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'

                bat 'mvn clean test package'
            }
        }
    }
    post{
        success{
            bat 'java -jar %jarlocation%'
        }
    }
}
